name: CMake Build and Release

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up CMake
      uses: lukka/get-cmake@latest

    - name: Configure CMake
      run: cmake -S . -B build

    - name: Build
      run: cmake --build build --config Release

    - name: Save build logs
      run: |
        # Store logs of the build process into a log file
        cmake --build build --config Release > build_output_${{ matrix.os }}.log || true

    - name: Archive build logs as artifacts
      uses: actions/upload-artifact@v3
      with:
        name: ${{ matrix.os }}-build-logs
        path: build_output_${{ matrix.os }}.log

    - name: Archive build artifacts
      uses: actions/upload-artifact@v3
      with:
        name: ${{ matrix.os }}-build
        path: build/
